# Generated by Django 5.2.1 on 2025-05-12 18:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_answer_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theory',
            fields=[
                ('theory_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание теории')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Теория',
                'verbose_name_plural': 'Теории',
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.topic', verbose_name='Тема')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия тренажёра',
                'verbose_name_plural': 'Сессии тренажёра',
            },
        ),
    ]
